# Unified Application Configuration
application:
  name: DevOpsSimulator
  version: 1.0.0
  environment: production
  
  # Experimental Mode (not production-ready)
  experimental_mode: false  # set to true to enable experimental configs
  # experimental_version: 3.0.0-experimental  # uncomment if testing new features

server:
  host: 0.0.0.0
  port: 8080
  ssl_enabled: true
  
  # Optional (development only)
  hot_reload: false  # set to true in development

  # --- Experimental Server Configurations ---
  # NOTE: These are experimental and not production-ready
  # experimental_multi_port: [9000, 9001, 9002]  # enable for multi-port testing

logging:
  level: INFO
  format: json
  output: /var/log/app.log
  
  # Optional (development only)
  show_stack_trace: false  # set to true in development
  
  # --- Experimental Logging Options ---
  # format: structured  # for AI-based log parsing
  # ai_analysis: enabled  # enables AI log insights (experimental)

database:
  host: prod-db.example.com
  port: 5432
  name: devops_prod
  
  # --- Experimental Database Settings ---
  # host: cluster.example.com
  # name: devops_experimental
  # distributed: true  # enable distributed DB setup (experimental)

features:
  auto_scaling: true
  load_balancer: enabled
  backup_enabled: true
  
  # Optional (development only)
  experimental_features: false  # enable in development if needed

  # --- Experimental Features ---
  # auto_scaling: advanced
  # load_balancer: ai-optimized
  # chaos_engineering: enabled  # inject failures for resilience testing

# Optional AI Feature Flags (Experimental)
ai_features:
  enabled: false  # global toggle for AI experimental features
  # predictive_scaling: true
  # anomaly_detection: true
  # auto_optimization: true
  # model_version: "v2.1.0"

# Optional Cloud Provider Integrations (Experimental)
cloud_providers:
  enabled: false
  # supported: [aws, azure, gcp, digitalocean]

# Optional Security Enhancements (Experimental)
security:
  zero_trust: false
  encryption: AES-256
  # audit_logging: comprehensive  # enable for enhanced tracking (experimental)

# Optional Development Configuration
development:
  enabled: false  # toggle true for development
  mock_external_apis: true
  debug_mode: true
  cors_enabled: true

# Optional Notifications (used in development/testing)
notifications:
  slack_webhook: "https://hooks.slack.com/services/XXX"
  discord_webhook: "https://discord.com/api/webhooks/YYY"
  email_alerts: false
