# Unified Application Configuration
application:
  name: DevOpsSimulator
  version: 1.0.0
  environment: production
  
server:
  host: 0.0.0.0
  port: 8080
  ssl_enabled: true
  # Optional (development only)
  hot_reload: false  # set to true in development
  
logging:
  level: INFO
  format: json
  output: /var/log/app.log
  # Optional (development only)
  show_stack_trace: false  # set to true in development
  
database:
  host: prod-db.example.com
  port: 5432
  name: devops_prod
  
features:
  auto_scaling: true
  load_balancer: enabled
  backup_enabled: true
  # Optional (development only)
  experimental_features: false  # enable in development if needed
  
# Optional Development Configuration
development:
  enabled: false  # toggle true for development
  mock_external_apis: true
  debug_mode: true
  cors_enabled: true

# Optional Notifications (used in development/testing)
notifications:
  slack_webhook: "https://hooks.slack.com/services/XXX"
  discord_webhook: "https://discord.com/api/webhooks/YYY"
  email_alerts: false
